### ISSUE TITLE
这段代码楼主确认可以运行吗？setRequestInterception(true),不处理request事件，页面加载就阻塞了吧

### ISSUE THREAD

**Issue by imfengzi** [jessieeeee/jessieeeee.github.io#4]
https://github.com/jessieeeee/jessieeeee.github.io/blob/a0d4c0a0b47a92f51f0eabc43797bde7b3c41d1b/2020/02/05/PuppeteerInterception/index.html#L328

**Comment by jessieeeee** [comment]
嗯，这个是在项目中跑过的代码
